package pl.edu.pwsztar.universityrecruitment;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class UniversityCandidate implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(generator = "UNIVERSITYCANDIDATE_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "UNIVERSITYCANDIDATE_ID_SEQ", name = "UNIVERSITYCANDIDATE_ID_GENERATOR")
   private java.lang.Long id;

   private java.lang.String firstName;

   private java.lang.String lastName;

   private java.lang.Integer examResult = 0;

   private java.lang.Boolean admission = Boolean.FALSE;

   private java.lang.String study;

   private java.lang.Boolean olympic = Boolean.FALSE;

   private java.lang.String logger = "";

   private java.lang.String qualificationType;

   public UniversityCandidate()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.lang.Integer getExamResult()
   {
      return this.examResult;
   }

   public void setExamResult(java.lang.Integer examResult)
   {
      this.examResult = examResult;
   }

   public java.lang.Boolean getAdmission()
   {
      return this.admission;
   }

   public void setAdmission(java.lang.Boolean admission)
   {
      this.admission = admission;
   }

   public java.lang.String getStudy()
   {
      return this.study;
   }

   public void setStudy(java.lang.String study)
   {
      this.study = study;
   }

   public java.lang.Boolean getOlympic()
   {
      return this.olympic;
   }

   public void setOlympic(java.lang.Boolean olympic)
   {
      this.olympic = olympic;
   }

   public java.lang.String getLogger()
   {
      return this.logger;
   }

   public void setLogger(java.lang.String logger)
   {
      this.logger = logger;
   }

   public void appendLogger(java.lang.String logger)
   {
      this.logger += logger + " | ";
   }

   public java.lang.String getQualificationType()
   {
      return this.qualificationType;
   }

   public void setQualificationType(java.lang.String qualificationType)
   {
      this.qualificationType = qualificationType;
   }

   public UniversityCandidate(java.lang.Long id, java.lang.String firstName,
         java.lang.String lastName, java.lang.Integer examResult,
         java.lang.Boolean admission, java.lang.String study,
         java.lang.Boolean olympic, java.lang.String logger,
         java.lang.String qualificationType)
   {
      this.id = id;
      this.firstName = firstName;
      this.lastName = lastName;
      this.examResult = examResult;
      this.admission = admission;
      this.study = study;
      this.olympic = olympic;
      this.logger = logger;
      this.qualificationType = qualificationType;
   }

}
